export default {
  SIZE: [
    {
      id: 1,
      name: '30см',
      slug: 'small',
      category: 'size',
    },
    {
      id: 2,
      name: '50см',
      slug: 'big',
      price: 50,
      category: 'size',
    },
  ],
  DOUGH: [
    {
      id: 1,
      name: 'Тонкое',
      slug: 'thin',
      category: 'dough',
    },
    {
      id: 2,
      name: 'Пышное',
      slug: 'lush',
      category: 'dough',
    },
  ],
  SAUCES: [
    {
      id: 1,
      name: 'Белый',
      slug: 'white',
      category: 'sauces',
    },
    {
      id: 2,
      name: 'Томатный',
      slug: 'tomatoSauce',
      category: 'sauces',
    },
    {
      id: 3,
      name: 'Острый',
      slug: 'hot',
      category: 'sauces',
    },
    {
      id: 4,
      name: 'Грибной',
      slug: 'mushroom',
      category: 'sauces',
    },
    {
      id: 5,
      name: 'Чесночный',
      slug: 'garlic',
      category: 'sauces',
    },
    {
      id: 6,
      name: 'Кисло-сладкий',
      slug: 'sweetSour',
      category: 'sauces',
    },
    {
      id: 7,
      name: 'Горчичный',
      slug: 'mustard',
      category: 'sauces',
    },
  ],
  CHEESES: [
    {
      id: 1,
      name: 'Моцарелла',
      slug: 'mozzarella',
      price: 29,
      category: 'cheeses',
    },
    {
      id: 2,
      name: 'Чеддер',
      slug: 'cheddar',
      price: 29,
      category: 'cheeses',
    },
    {
      id: 3,
      name: 'Дор Блю',
      slug: 'dorBlue',
      price: 29,
      category: 'cheeses',
    },
  ],
  VEGETABLES: [
    {
      id: 1,
      name: 'Помидоры',
      slug: 'tomato',
      price: 29,
      category: 'vegetables',
    },
    {
      id: 2,
      name: 'Грибы',
      slug: 'mushrooms',
      price: 29,
      category: 'vegetables',
    },
    {
      id: 3,
      name: 'Перец',
      slug: 'pepper',
      price: 29,
      category: 'vegetables',
    },
    {
      id: 4,
      name: 'Ананасы',
      slug: 'pineapple',
      price: 29,
      category: 'vegetables',
    },
    {
      id: 5,
      name: 'Оливки',
      slug: 'olives',
      price: 29,
      category: 'vegetables',
    },
    {
      id: 6,
      name: 'Лук',
      slug: 'onion',
      price: 29,
      category: 'vegetables',
    },
    {
      id: 7,
      name: 'Брокколи',
      slug: 'broccoli',
      price: 29,
      category: 'vegetables',
    },
  ],
  MEAT: [
    {
      id: 1,
      name: 'Бекон',
      slug: 'bacon',
      price: 29,
      category: 'meat',
    },
    {
      id: 2,
      name: 'Пеперонни',
      slug: 'pepperoni',
      price: 29,
      category: 'meat',
    },
    {
      id: 3,
      name: 'Ветчина',
      slug: 'ham',
      price: 29,
      category: 'meat',
    },
    {
      id: 4,
      name: 'Курица',
      slug: 'chicken',
      price: 29,
      category: 'meat',
    },
    {
      id: 5,
      name: 'Салями',
      slug: 'salami',
      price: 29,
      category: 'meat',
    },
  ],
};
